### ISSUE TITLE
[BUG] "CATNIP" example not working - Python problem

### ISSUE THREAD

**Issue by hfatgit** [prakhar1989/docker-curriculum#309]
**Describe the bug**
"catnip" example is failing to start

**To Reproduce**
Simply following the instructions given in the tutorial. 
- cloning docker-curriculum from git
- changing directory to flask-app (not changing/editing any files)
- running docker build
- starting compiled container

**Expected behavior**
Running catnip container as described in the tutorial 

**Erratic behaviour**
$ docker run -p 8888:5000 awpwh/catnip
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 34, in <module>
    from .sessions import SecureCookieSessionInterface
  File "/usr/local/lib/python3.10/site-packages/flask/sessions.py", line 14, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

**Desktop:**
 - OS: Windows10
 - Docker Version Docker version 20.10.9, build c2ea9bc
- Running Docker in WSL 2

**Comment by JohnFowlerDXC** [comment]
If you want to continue using the current version of Python, you can also change it to use the current version of Flask.  Flask is currently forced to version 1.0 in requirements.txt, and version 1.0 doesn't work with Python 3.10.

**Comment by prakhar1989** [comment]
I'm unable to reproduce this issue locally. I've bumped the Flask version, can you re-try and see if this issue persists for you?
